using Random
using LinearAlgebra

"""
    struct NNFlip <: AbstractMCMove
    
Struct of Type Abstract MC Move, that holds basic information about the NN-based update such as model-size (update size), test lattice size, and a neighbour mask used for 
efficient updates.

# Attributes    
`neighbour_mask::Vector{Int}` : mask allowing efficient neighbour computation for proposing a move
`model_size::Int  `  : size of model
`test_size::Int ` : size of system
"""
struct NNFlip <: AbstractMCMove
    neighbour_mask::Vector{Int}
    model_size::Int 
    test_size::Int 
end

"""
    struct NNFlipInfo 
    
Struct that stores the sub-lattice to be updated, with the sub-lattice computed considering the "site" to be the bottom-left corner of the sub-lattice.

# Attributes    
`site::CartesianIndex` : Cartesian index of the site to be updated
`sub_system::Array{Int, 2}` : Exact spins in the sub-lattice to be updated, stored as matrix preserving their spatial relations.
`sub_sys_indices:: Array{CartesianIndex}` : Cartesian Indices in the sub-lattice.
`sys_indices:: Array{CartesianIndex}` : Cartesian Indices in the full-lattice, with the list indices corresponding to those in the "sub_sys_indices
"""
struct NNFlipInfo  # M is model_size
    site::CartesianIndex 
    sub_system::Array{Int, 2}
    sub_sys_indices:: Array{CartesianIndex}
    sys_indices:: Array{CartesianIndex}
end

"""
    function NNFlip(model_size::Int, test_size::Int) 

Constructor function to initialize an object of NNFlip type. 
"""
function NNFlip(model_size::Int, test_size::Int) 
    mask = [Int(i) for i in 0:model_size-1]
    return NNFlip(mask, model_size, test_size)
end

""" 
    function compute_sub_system(site_index::CartesianIndex , flip_object::NNFlip, system)

Function to compute the sub-lattice to be updated, given index of the "top-left" side from the flip-object struct.
"""
function compute_sub_system(site_index::CartesianIndex , flip_object::NNFlip, system)
    i, j = Tuple(site_index)
    neigh_mask = flip_object.neighbour_mask
    x_indices = mod1.(i .+ neigh_mask , flip_object.test_size)
    y_indices = mod1.(j .+ neigh_mask , flip_object.test_size)

    sub_sys = ones(Int, flip_object.model_size, flip_object.model_size)

    sub_sys_indices = CartesianIndex[] # make 2 lists to store correspnonding indices of system and sub-system
    sys_indices = CartesianIndex[]
    for i in neigh_mask
        for j in neigh_mask
            sub_sys_idx = CartesianIndex(i+1 , j+1) # index in sub-system
            sys_idx = CartesianIndex(x_indices[i+1], y_indices[j+1]) # index in larger system

            # update sub-system here so 1 less for-loop in the run_model function. 
            sub_sys[sub_sys_idx] = system[sys_idx] 
            push!(sub_sys_indices, sub_sys_idx) # store indices also.
            push!(sys_indices, sys_idx)
        end
    end

    FlipInfo = NNFlipInfo(site_index, sub_sys, sub_sys_indices, sys_indices)

    return FlipInfo

end
    

"""
    test_model(model, model_size, test_size, num_runs, init, hyp, J::Float64, H::Float64)

Test a trained neural-network sampler by generating a Markov chain and recording observables
(when the NN output is sitewise spin flip probablilites)

This function initializes a spin system, repeatedly proposes local updates using the model, and records the evolution of energy, magnetization, and system
configurations. 

# Arguments
- `model`: Trained neural network used to propose or evaluate updates.
- `model_size`: Linear size of the subsystem on which the model acts.
- `test_size`: Linear size of the full lattice used for testing.
- `num_runs::Int`: Number of Monte Carlo update steps to perform.
- `init`: Initialization mode for the system (`"random"` or uniform).
- `hyp`: beta value (inverse temperature)
- `J::Float64`: Ising interaction strength
- `H::Float64`: External magnetic field

# Returns
- `energies::Vector{Float64}`: Energies of the sampled system states.
- `observables::Vector{Float64}`: Magnetizations of the sampled system states.
- `system_list`: Vector of system configurations generated by MCMC chain.
- `update_indices`: Indices of lattice sites where updates were proposed 
- `acceptance_rate::Float64`: Fraction of accepted proposed updates

# Notes
- The initial configuration is included as the first element of the returned time series.
- Periodic boundary conditions and detailed balance are assumed to be enforced by the proposal and acceptance routines.
"""
function test_model(model, model_size, test_size, num_runs, init, hyp, J::Float64, H::Float64)

    # initialize system, according to init
    system_init = 1 * ones(Int, test_size, test_size) # by default initialize system anti-aligned to H
    if init=="random"
        system_init = sign.(rand(test_size, test_size) .*2 .-1 ) # set system as sign of random numbers between -1 and 1.
    end
    # use Ising Hamiltonian struct to store J and H 
    ham = IsingHamiltonian(J, H)

    # initialize lists to store evolution of magentization and energy as the simulation runs.
    energies = Float64[] 
    observables = Float64[]
    system_list = []
    update_indices = []
    acceptance = 0 
    push!(system_list, system_init)
    push!(energies, calculate_total_Energy(system_init, ham))
    push!(observables, Float64(magnetization(system_init)))

    NNFlipObj = NNFlip(model_size, test_size)
    
    # iterate over several runs
    for i in 1:num_runs
        
        system = system_list[i] 
        FlipInfo = propose_move(system, NNFlipObj) 
        accept = run_model!(model, hyp, system, FlipInfo, ham)

        acceptance += accept 

        push!(update_indices, FlipInfo.site) # store index that was updated to verify uniformity.
        push!(system_list, copy(system)) # store copy of the system after this update.
        push!(energies, calculate_total_Energy(system, ham))
        push!(observables, Float64(magnetization(system)))
        
    end

    return energies, observables, system_list, update_indices, (acceptance/num_runs)
end



""" 
    function propose_move(system, NNFlip)

Function to pick a random site in the model, and identify and return a FlipInfo object containing information about the sub-lattice to be updated.
"""
function propose_move(system, NNFlip)

    cartesian_indices = CartesianIndices(system) 
    random_index = rand(eachindex(cartesian_indices)) # get random index that is the "BOTTOM LEFT" corner of the grid to be updated.
    spin_site = cartesian_indices[random_index]
   
    FlipInfo = compute_sub_system(spin_site, NNFlip, system)

    return FlipInfo

end

"""
    function update_system!(updated_sub_sys, FlipInfo::NNFlipInfo, system)

Given the updated_sub_system, write it according to the correct indices, in the full-system.
"""
function update_system!(updated_sub_sys, FlipInfo::NNFlipInfo, system)
    for (idx, val) in enumerate(FlipInfo.sub_sys_indices)
        system[Tuple(FlipInfo.sys_indices[idx])...] = updated_sub_sys[Tuple(val)...] 
    end 
end

"""
    function run_model!(model, hyp, system, FlipInfo, ham::IsingHamiltonian)

Given proposal information about the sub-lattice, this function applies the NN to the sub-lattice, computes acceptance probability according to Metropolis-Hastings, 
and updates the system if the move is accepted.
"""
function run_model!(model, hyp, system, FlipInfo, ham::IsingHamiltonian)

    # run model on proposed 
    sub_system = reshape(FlipInfo.sub_system, size(FlipInfo.sub_system)..., 1, 1)# reshape system to 4d vector.
    hyp = Float32(hyp) 
    probs = model(sub_system, hyp) 

    updated_sub_sys = advance_system(sub_system, probs)
    inverse_probs = model(updated_sub_sys, hyp)     # find CNN_probs from (new->old)
    updated_sub_sys, MH_prob = get_MH_acceptance_prob(probs,  updated_sub_sys, inverse_probs, hyp, sub_system, ham)
    accept = (MH_prob >= rand()) # decide wether to accept or not

    if accept
        update_system!(updated_sub_sys, FlipInfo, system)
    end

    return accept
end

""" 
    function advance_system(sub_system, probs)

Given site-wise probabilites of flipping (NN output) and the sub-system to be updated, randomly-flip the spins in the sub-system according 
to the given probabilities, and returen the proposed system.
"""
function advance_system(sub_system, probs)
    flip = probs[:,:,1,1] .>= rand(size(sub_system)...) # get boolean mask of wether site will flip or not.
    updated_sub_sys = sub_system .* (1 .- 2 .* flip) # proposed state
    return updated_sub_sys
end

"""
    function get_MH_acceptance_prob(probs, updated_sub_sys, inverse_probs, hyp, sub_system, ham::IsingHamiltonian)
    
Given a sub-system and the proposed next-subsystem (along with site-wise probabilites of flipping both ways), compute the 
Metropolis-Hastings accceptance probability of the move.
"""
function get_MH_acceptance_prob(probs, updated_sub_sys, inverse_probs, hyp, sub_system, ham::IsingHamiltonian)

    
    # for now, approximate energy difference using only field term (16x16 grid instead of 18x18)
    delta_E = calculate_total_Energy(updated_sub_sys, ham) - calculate_total_Energy(sub_system, ham)
    exp_deltaE = exp( -delta_E * hyp)

    hastings_term = prod(probs ./ inverse_probs) 

    acceptance_prob = min(exp_deltaE * hastings_term, 1.0)

    return updated_sub_sys, acceptance_prob

end

"""
    function calculate_total_Energy(x, ham::IsingHamiltonian) 

Efficiently calculate the total energy of the spin system, according to the Ising Hamiltonian.
"""
function calculate_total_Energy(x, ham::IsingHamiltonian) 
    x_down = circshift(x,(-1,0))
    x_right = circshift(x,(0,-1))

    interaction = -ham.J * sum(x.* x_down .+ x .* x_right )
    field = -ham.h * sum(x)
    total_energy = interaction + field

    return total_energy
end



